#!/usr/bin/env bash
# Manage ephemeral OpenClaw Docker instances for evolve_eval.
# Registry: /tmp/evolve-eval-openclaw-instances/<id>.env (not ~/.openclaw on host)
#
# Usage (from repo root):
#   ./agent-runtimes/openclaw/scripts/openclaw-instance.sh create --id run-a
#   ./agent-runtimes/openclaw/scripts/openclaw-instance.sh list
#   ./agent-runtimes/openclaw/scripts/openclaw-instance.sh env run-a
#   ./agent-runtimes/openclaw/scripts/openclaw-instance.sh destroy run-a

set -euo pipefail

REGISTRY_DIR="${OPENCLAW_INSTANCE_REGISTRY:-/tmp/evolve-eval-openclaw-instances}"
IMAGE="${OPENCLAW_IMAGE:-evolve-eval-openclaw-with-evolve:latest}"
BASE_GATEWAY_PORT="${OPENCLAW_BASE_GATEWAY_PORT:-18789}"
BASE_FASTAPI_PORT="${OPENCLAW_BASE_FASTAPI_PORT:-18090}"
PORT_STEP="${OPENCLAW_PORT_STEP:-20}"
CONTAINER_PREFIX="${OPENCLAW_CONTAINER_PREFIX:-evolve-openclaw}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"

load_repo_env() {
  if [[ -f "${REPO_ROOT}/.env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "${REPO_ROOT}/.env"
    set +a
  fi
}

registry_file() {
  local id="$1"
  echo "${REGISTRY_DIR}/${id}.env"
}

sanitize_id() {
  local id="$1"
  if [[ ! "${id}" =~ ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$ ]]; then
    echo "Invalid instance id: ${id} (use letters, digits, ., _, -)" >&2
    exit 1
  fi
}

container_name() {
  echo "${CONTAINER_PREFIX}-$1"
}

next_instance_index() {
  mkdir -p "${REGISTRY_DIR}"
  local max=-1
  local f base idx
  for f in "${REGISTRY_DIR}"/*.env; do
    [[ -f "${f}" ]] || continue
    base="$(basename "${f}" .env)"
    if [[ "${base}" =~ ^instance-([0-9]+)$ ]]; then
      idx="${BASH_REMATCH[1]}"
      if (( idx > max )); then
        max="${idx}"
      fi
    fi
  done
  # Also consider running containers with our prefix
  local names
  while IFS= read -r names; do
    [[ -n "${names}" ]] || continue
    if [[ "${names}" =~ ${CONTAINER_PREFIX}-instance-([0-9]+) ]]; then
      idx="${BASH_REMATCH[1]}"
      if (( idx > max )); then
        max="${idx}"
      fi
    fi
  done < <(docker ps -a --format '{{.Names}}' 2>/dev/null | grep "^${CONTAINER_PREFIX}-" || true)
  echo $((max + 1))
}

allocate_ports() {
  local index="$1"
  OPENCLAW_GATEWAY_HOST_PORT=$((BASE_GATEWAY_PORT + index * PORT_STEP))
  OPENCLAW_FASTAPI_HOST_PORT=$((BASE_FASTAPI_PORT + index * PORT_STEP))
}

wait_gateway() {
  local port="$1"
  local tries="${2:-60}"
  local i
  for ((i = 0; i < tries; i++)); do
    if curl -sf "http://127.0.0.1:${port}/" >/dev/null 2>&1 \
      || curl -sf "http://127.0.0.1:${port}/health" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done
  return 1
}

cmd_create() {
  local id=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --id) id="$2"; shift 2 ;;
      *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
  done

  load_repo_env

  if [[ -z "${id}" ]]; then
    local idx
    idx="$(next_instance_index)"
    id="instance-${idx}"
  fi
  sanitize_id "${id}"

  local reg
  reg="$(registry_file "${id}")"
  if [[ -f "${reg}" ]]; then
    echo "Instance already registered: ${id} (${reg})" >&2
    echo "Destroy first: $0 destroy ${id}" >&2
    exit 1
  fi

  local cname
  cname="$(container_name "${id}")"
  if docker ps -a --format '{{.Names}}' | grep -qx "${cname}"; then
    echo "Container name already in use: ${cname}" >&2
    exit 1
  fi

  local idx_for_ports=0
  if [[ "${id}" =~ ^instance-([0-9]+)$ ]]; then
    idx_for_ports="${BASH_REMATCH[1]}"
  else
    idx_for_ports="$(next_instance_index)"
  fi
  allocate_ports "${idx_for_ports}"

  local token
  if command -v openssl >/dev/null 2>&1; then
    token="$(openssl rand -hex 32)"
  else
    token="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  fi

  mkdir -p "${REGISTRY_DIR}"

  echo "Creating ${cname} (image=${IMAGE})"
  echo "  gateway host port: ${OPENCLAW_GATEWAY_HOST_PORT}"
  echo "  fastapi host port: ${OPENCLAW_FASTAPI_HOST_PORT}"

  docker run -d \
    --name "${cname}" \
    -p "${OPENCLAW_GATEWAY_HOST_PORT}:18789" \
    -p "${OPENCLAW_FASTAPI_HOST_PORT}:18090" \
    -v /tmp:/tmp \
    -e "OPENCLAW_GATEWAY_TOKEN=${token}" \
    -e "ARK_API_KEY=${ARK_API_KEY:-}" \
    -e "LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-}" \
    -e "LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY:-}" \
    -e "LANGFUSE_BASE_URL=${LANGFUSE_BASE_URL:-http://host.docker.internal:3000}" \
    "${IMAGE}" >/dev/null

  echo "Waiting for gateway on :${OPENCLAW_GATEWAY_HOST_PORT} ..."
  if ! wait_gateway "${OPENCLAW_GATEWAY_HOST_PORT}" 90; then
    echo "WARN: gateway health check timed out; check: docker logs ${cname}" >&2
  fi

  cat > "${reg}" <<EOF
# Generated by openclaw-instance.sh — source via: eval "\$($0 env ${id})"
OPENCLAW_INSTANCE_ID=${id}
OPENCLAW_CONTAINER=${cname}
OPENCLAW_GATEWAY_HOST_PORT=${OPENCLAW_GATEWAY_HOST_PORT}
OPENCLAW_FASTAPI_HOST_PORT=${OPENCLAW_FASTAPI_HOST_PORT}
OPENCLAW_GATEWAY_TOKEN=${token}
OPENCLAW_GATEWAY_URL=http://127.0.0.1:${OPENCLAW_GATEWAY_HOST_PORT}
OPENCLAW_IMAGE=${IMAGE}
EOF

  echo "Registered: ${reg}"
  echo ""
  echo "Use on host:"
  echo "  eval \"\$($0 env ${id})\""
}

cmd_list() {
  mkdir -p "${REGISTRY_DIR}"
  if ! ls "${REGISTRY_DIR}"/*.env >/dev/null 2>&1; then
    echo "No instances under ${REGISTRY_DIR}"
    return 0
  fi
  printf "%-16s %-28s %-8s %-8s %-10s\n" "ID" "CONTAINER" "GW_PORT" "API_PORT" "RUNNING"
  local f id cname gw api running
  for f in "${REGISTRY_DIR}"/*.env; do
    [[ -f "${f}" ]] || continue
    # shellcheck disable=SC1090
    source "${f}"
    id="${OPENCLAW_INSTANCE_ID:-$(basename "${f}" .env)}"
    cname="${OPENCLAW_CONTAINER:-$(container_name "${id}")}"
    gw="${OPENCLAW_GATEWAY_HOST_PORT:-?}"
    api="${OPENCLAW_FASTAPI_HOST_PORT:-?}"
    if docker ps --format '{{.Names}}' | grep -qx "${cname}"; then
      running="yes"
    else
      running="no"
    fi
    printf "%-16s %-28s %-8s %-8s %-10s\n" "${id}" "${cname}" "${gw}" "${api}" "${running}"
  done
}

cmd_env() {
  local id="${1:-}"
  if [[ -z "${id}" ]]; then
    echo "Usage: $0 env <instance-id>" >&2
    exit 1
  fi
  sanitize_id "${id}"
  local reg
  reg="$(registry_file "${id}")"
  if [[ ! -f "${reg}" ]]; then
    echo "Unknown instance: ${id} (no ${reg})" >&2
    exit 1
  fi
  grep -E '^[A-Z_]+=' "${reg}" | sed 's/^/export /'
}

cmd_commit() {
  local id=""
  local tag=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --tag) tag="$2"; shift 2 ;;
      *) id="$1"; shift ;;
    esac
  done
  if [[ -z "${id}" || -z "${tag}" ]]; then
    echo "Usage: $0 commit <instance-id> --tag IMAGE_TAG" >&2
    exit 1
  fi
  sanitize_id "${id}"
  local reg cname
  reg="$(registry_file "${id}")"
  cname="$(container_name "${id}")"
  if [[ -f "${reg}" ]]; then
    # shellcheck disable=SC1090
    source "${reg}"
    cname="${OPENCLAW_CONTAINER:-${cname}}"
  fi
  if ! docker ps -a --format '{{.Names}}' | grep -qx "${cname}"; then
    echo "Container not found: ${cname}" >&2
    exit 1
  fi
  docker commit "${cname}" "${tag}" >/dev/null
  echo "Committed ${cname} -> ${tag}"
  if [[ -f "${reg}" ]]; then
    echo "OPENCLAW_DELTA_IMAGE=${tag}" >> "${reg}"
  fi
}

cmd_destroy() {
  local id="${1:-}"
  if [[ -z "${id}" ]]; then
    echo "Usage: $0 destroy <instance-id>" >&2
    exit 1
  fi
  sanitize_id "${id}"
  local reg cname
  reg="$(registry_file "${id}")"
  cname="$(container_name "${id}")"
  if [[ -f "${reg}" ]]; then
    # shellcheck disable=SC1090
    source "${reg}"
    cname="${OPENCLAW_CONTAINER:-${cname}}"
  fi
  if docker ps -a --format '{{.Names}}' | grep -qx "${cname}"; then
    docker rm -f "${cname}" >/dev/null
    echo "Removed container ${cname}"
  else
    echo "Container not found: ${cname}"
  fi
  if [[ -f "${reg}" ]]; then
    rm -f "${reg}"
    echo "Removed registry ${reg}"
  fi
}

usage() {
  cat <<EOF
Usage: $0 <command> [args]

Commands:
  create [--id NAME]   Start a new instance (default id: instance-N)
  list               List registered instances
  env <id>           Print export statements for shell eval
  commit <id> --tag IMAGE_TAG
                     Commit running container to a delta image tag
  destroy <id>       Stop container and remove registry file

Environment:
  OPENCLAW_IMAGE              (default: evolve-eval-openclaw-with-evolve:latest)
  OPENCLAW_INSTANCE_REGISTRY  (default: /tmp/evolve-eval-openclaw-instances)
  Repo .env supplies ARK_API_KEY, LANGFUSE_*, etc.

Build image first:
  bash agent-runtimes/openclaw/build-image.sh
EOF
}

main() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "docker not found on PATH" >&2
    exit 127
  fi
  if ! docker info >/dev/null 2>&1; then
    echo "Cannot connect to Docker daemon" >&2
    exit 1
  fi

  local cmd="${1:-}"
  shift || true
  case "${cmd}" in
    create) cmd_create "$@" ;;
    list) cmd_list ;;
    env) cmd_env "$@" ;;
    commit) cmd_commit "$@" ;;
    destroy) cmd_destroy "$@" ;;
    -h|--help|help|"") usage ;;
    *) echo "Unknown command: ${cmd}" >&2; usage; exit 1 ;;
  esac
}

main "$@"
